fix issue where immutable check was done after the list size was checked resulting into an error being thrown for props that are actually mutable
- the unit test was not capturing this use case because the input list size
was matching the updated one not triggering the list size difference.

Example error:
Error: validation for immutable properties failed: immutable list property 'owners' size updated: [input list size: 6; remote list size: 5]. Update operation was aborted; no updates were performed