add support for request headers in operations
	cody@C02DL2WDMD6T swaggercodegen % cd - && PROVIDER_NAME="swaggercodegen" make install && cd - && rm -f .terraform.lock.hcl && terraform init && OTF_INSECURE_SKIP_VERIFY="true" OTF_VAR_swaggercodegen_SWAGGER_URL="https://localhost:8443/openapiv3.yaml" terraform apply
	~/git/go/src/github.com/dikhan/terraform-provider-openapi
	[INFO] Building terraform-provider-openapi binary
	2021-09-25 23:25:11 [INFO] Using the pre-compiled OpenAPI Terraform Plugin specified: terraform-provider-openapi v2.2.0
	2021-09-25 23:25:12 [INFO] Detected Terraform v0.15.5
	2021-09-25 23:25:12 [INFO] Installing provider based on Terraform >= v0.13.* plugin installation instructions: https://www.terraform.io/docs/configuration/provider-requirements.html#in-house-providers
	Terraform provider successfully installed!
	 |--> Installation Path: /Users/cody/.terraform.d/plugins/terraform.example.com/examplecorp/swaggercodegen/2.2.0/darwin_amd64/terraform-provider-swaggercodegen
	 |--> Important Note: As of Terraform >=0.13 each Terraform module must declare which providers it requires, so that Terraform can install and use them. You can copy into your .tf file the following snippet was autogenerated for your convenience based on the input provided:

	terraform {
	  required_providers {
	    swaggercodegen = {
	      source  = "terraform.example.com/examplecorp/swaggercodegen"
	      version = ">= 2.2.0"
	    }
	  }
	}
	~/git/go/src/github.com/dikhan/terraform-provider-openapi/examples/swaggercodegen

	Initializing the backend...

	Initializing provider plugins...
	- Finding terraform.example.com/examplecorp/swaggercodegen versions matching ">= 2.0.0"...
	- Installing terraform.example.com/examplecorp/swaggercodegen v2.2.0...
	- Installed terraform.example.com/examplecorp/swaggercodegen v2.2.0 (unauthenticated)

	Terraform has created a lock file .terraform.lock.hcl to record the provider
	selections it made above. Include this file in your version control repository
	so that Terraform can guarantee to make the same selections by default when
	you run "terraform init" in the future.

	Terraform has been successfully initialized!

	You may now begin working with Terraform. Try running "terraform plan" to see
	any changes that are required for your infrastructure. All Terraform commands
	should now work.

	If you ever set or change modules or backend configuration for Terraform,
	rerun this command to reinitialize your working directory. If you forget, other
	commands will detect it and remind you to do so if necessary.
	swaggercodegen_lbs_v1.my_lb: Refreshing state... [id=23ad1228-c34a-4e1c-be9e-fbf9fa6f9d06]
	swaggercodegen_cdn_v1.my_cdn: Refreshing state... [id=64c90722-d6d8-4fa7-b790-c958d6763710]
	╷
	│ Error: Plugin did not respond
	│
	│   with swaggercodegen_cdn_v1.my_cdn,
	│   on main.tf line 17, in resource "swaggercodegen_cdn_v1" "my_cdn":
	│   17: resource "swaggercodegen_cdn_v1" "my_cdn" {
	│
	│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
	╵
	╷
	│ Error: Plugin did not respond
	│
	│   with swaggercodegen_lbs_v1.my_lb,
	│   on main.tf line 90, in resource "swaggercodegen_lbs_v1" "my_lb":
	│   90: resource "swaggercodegen_lbs_v1" "my_lb" {
	│
	│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
	╵

	Stack trace from the terraform-provider-swaggercodegen plugin:

	panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x191b88b]

	goroutine 123 [running]:
	github.com/dikhan/terraform-provider-openapi/v2/openapi.(*ProviderClient).performRequest(0xc00033c230, {0x1b41958, 0xc000a84ba0}, {0xc00003e5f0, 0x43}, 0x0, {0x0, 0x0}, {0x19b1460, 0xc000120990})
		/Users/cody/git/go/src/github.com/dikhan/terraform-provider-openapi/openapi/openapi_client.go:101 +0x6b
	github.com/dikhan/terraform-provider-openapi/v2/openapi.(*ProviderClient).Get(0xc00033c230, {0x1d15c18, 0xc000550e80}, {0xc00003df80, 0xc000550e80}, {0x19b1460, 0xc000120990}, {0x23e29d0, 0x0, 0x0})
		/Users/cody/git/go/src/github.com/dikhan/terraform-provider-openapi/openapi/openapi_client.go:72 +0x1d3
	github.com/dikhan/terraform-provider-openapi/v2/openapi.resourceFactory.readRemote({{0x1d15c18, 0xc000550e80}, 0x8bb2c97000, 0x12a05f200, 0x2540be400, 0x3b9aca00}, {0xc00003df80, 0x24}, {0x2a0c9500, 0xc00033c230}, ...)
		/Users/cody/git/go/src/github.com/dikhan/terraform-provider-openapi/openapi/resource_factory.go:167 +0xf2
	github.com/dikhan/terraform-provider-openapi/v2/openapi.resourceFactory.readWithOptions({{0x1d15c18, 0xc000550e80}, 0x8bb2c97000, 0x12a05f200, 0x2540be400, 0x3b9aca00}, 0xc000a83100, {0x1af3180, 0xc00033c230}, 0x0)
		/Users/cody/git/go/src/github.com/dikhan/terraform-provider-openapi/openapi/resource_factory.go:146 +0x26f
	github.com/dikhan/terraform-provider-openapi/v2/openapi.resourceFactory.read(...)
		/Users/cody/git/go/src/github.com/dikhan/terraform-provider-openapi/openapi/resource_factory.go:161
	github.com/dikhan/terraform-provider-openapi/v2/openapi.crudWithContext.func1.1()
		/Users/cody/git/go/src/github.com/dikhan/terraform-provider-openapi/openapi/common.go:21 +0x36
	created by github.com/dikhan/terraform-provider-openapi/v2/openapi.crudWithContext.func1
		/Users/cody/git/go/src/github.com/dikhan/terraform-provider-openapi/openapi/common.go:21 +0x146

	Error: The terraform-provider-swaggercodegen plugin crashed!

	This is always indicative of a bug within the plugin. It would be immensely
	helpful if you could report the crash with the plugin's maintainers so that it
	can be fixed. The output above should help diagnose the issue.